"""Update all tables

Revision ID: 96ea5a4f669e
Revises: a6c59568c0ca
Create Date: 2025-07-20 18:18:32.377673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ea5a4f669e'
down_revision: Union[str, Sequence[str], None] = 'a6c59568c0ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_foreign_key(None, 'contacts', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'hashed_password')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=True)
    op.drop_column('contacts', 'user_id')
    # ### end Alembic commands ###
